# Generated by Django 4.2.6 on 2023-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
